<a href="https://colab.research.google.com/github/piserushikesh/Gen_AI_Training/blob/main/Creating_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Zeros

In [1]:
import numpy as np

ar_zeros = np.zeros(4)
ar_zeros1 = np.zeros((3,4))


print(ar_zeros)
print()
print(ar_zeros1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Once

In [3]:
ar_once = np.ones(4)

print(ar_once)

[1. 1. 1. 1.]


Range

In [4]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


Diagonal

In [5]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linSpace

In [6]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


Create arrays with random numbers ----> rand() randn() ranf() randint()

rand()  values between 0 to 1 only

In [8]:
var = np.random.rand(4)
print(var)

[0.15197298 0.00949707 0.97264536 0.18403411]


In [9]:
var1 = np.random.rand(2,5)
print(var1)

[[0.43847417 0.33817964 0.2822436  0.65423481 0.32224469]
 [0.52584278 0.45290997 0.17763119 0.71944251 0.12703079]]


randn() return value 0 to 1 but it may be positive or negative

In [10]:
var2 = np.random.randn(2,5)
print(var2)

[[ 0.28882685  0.21470821 -0.18034696 -0.57672865 -0.46784228]
 [-0.51427645 -0.19947336 -1.34121759  0.38606369  0.56875753]]


In [11]:
var3 = np.random.ranf(4)
print(var3)

[0.57253159 0.23012117 0.35216398 0.79476716]


In [12]:
var4 = np.random.randint(5,25,6)
print(var4)

[ 8  6  6 20 12 22]
