<a href="https://colab.research.google.com/github/piserushikesh/Gen_AI_Training/blob/main/NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array

In [3]:
import numpy as np

x=[1,2,3,4]

y = np.array([1,2,3,4,5])

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [2]:
l = []

for i in range(1,5):
  int_1 = int(input("enter : "))
  l.append(int_1)

print(np.array(l))

enter : 23
enter : 32
enter : 45
enter : 11
[23 32 45 11]


In [4]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2
