<a href="https://colab.research.google.com/github/piserushikesh/Gen_AI_Training/blob/main/NumPy_Arrays_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Search

In [2]:
import numpy as np

var = np.array([1,2,3,4,5,2,6,7,8,3,2,9])

x = np.where( var == 2)

print(x)

(array([ 1,  5, 10]),)


In [3]:
var1 = np.array([1,2,3,4,5,8,9])

x1 = np.searchsorted( var1,6)

print(x1)

5


In [4]:
var2 = np.array([23,43,2,45,76,12])

x2 = np.sort(var2)

print(x2)

[ 2 12 23 43 45 76]


In [8]:
var3 = np.array([23,43,2,45,76,12])

x3 = np.random.shuffle(var3)

print(var3)

[23 76  2 43 12 45]


In [11]:
var9 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var9,2,[22,23,24], axis = 0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [14]:
v2 = np.delete(v1,0)

print(v2)

[ 2  3  1  2  3 22 23 24]
